# Generated by Django 4.0.5 on 2022-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gh_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
