# Generated by Django 4.0.5 on 2022-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_credit',
            field=models.IntegerField(default=0),
        ),
    ]
