# Generated by Django 4.0.5 on 2023-02-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_authtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
    ]
