# Generated by Django 4.0.5 on 2023-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification_link_notification_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('hobby', 'hobby'), ('pro', 'pro'), ('enterprise', 'enterprise')], default='hobby', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='USD', max_length=4),
        ),
    ]
