# Generated by Django 4.0.5 on 2023-03-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('users', '0011_userprofile_phone_number_userprofile_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_channel_layer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authtokens',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='authtoken.token'),
        ),
    ]
