# Generated by Django 4.0.5 on 2023-03-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
