# Generated by Django 4.0.5 on 2022-12-09 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(blank=True, max_length=5)),
                ('card_token', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MMPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField()),
                ('transaction_status', models.CharField(default='pending', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billing.card')),
                ('mm_phone_number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billing.mmphonenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
