# Generated by Django 4.0.5 on 2022-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
