# Generated by Django 4.0.5 on 2022-12-11 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0021_project_last_charged_project_plan'),
        ('billing', '0002_transaction_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='card',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mmphonenumber',
            name='country',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.project'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verification_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
