# Generated by Django 4.0.5 on 2023-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_transaction_id_card_automatic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
