# Generated by Django 4.0.5 on 2023-01-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_country_userprofile_created_at_and_more'),
        ('billing', '0004_card_card_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmphonenumber',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
            preserve_default=False,
        ),
    ]
