# Generated by Django 4.0.5 on 2023-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_mmphonenumber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmphonenumber',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
