# Generated by Django 4.0.5 on 2023-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_transaction_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
