# Generated by Django 4.0.5 on 2023-01-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_card_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fw_id',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
