# Generated by Django 4.0.5 on 2023-10-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_notification_options'),
        ('billing', '0010_transaction_fw_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='project',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('settled', models.BooleanField(default=False)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billing'),
        ),
    ]
