image:
  file: .gitpod.Dockerfile

tasks:
  - name: Python Terminal
    before: |
      python3 -m venv .venv 
      source .venv/bin/activate
      pip3 install -r requirements.txt 
    init: python3 manage.py migrate