image:
  file: .gitpod.Dockerfile

tasks:
  - name: Python Terminal
    before: |
      chmod a+w /var/run/docker.sock
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
      chmod +x ./kind
      sudo mv ./kind /usr/local/bin/kind
      python3 -m venv .venv 
      source .venv/bin/activate
      pip3 install -r requirements.txt 
    init: python3 manage.py migrate