image:
  file: .gitpod.Dockerfile

tasks:
  - name: Python Terminal
    before: |
      kind create cluster --config .config/kind-config.yml
      python3 -m venv .venv 
      source .venv/bin/activate
      pip3 install -r requirements.txt 
    init: python3 manage.py migrate
    command: python3 manage.py runserver