"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY", 'django-insecure-55pd&v_pb@na(x%ar@pm&k2%dvlo3qn+^0@lo$-v6qd3y99c=6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'rest_framework_simplejwt',
    "corsheaders",
    "deployments",
    "users",
    "anymail",
    "channels",
    "billing",
    "intergrations",
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ANYMAIL = {
    # (exact settings here depend on your ESP...)
    "MAILGUN_API_KEY": "5665624917222649a8cd6d5bcc644cf7-2bab6b06-ef64d8fd",
    "MAILGUN_SENDER_DOMAIN": 'sandbox1bab856e0f3d46a3a39af5b09cc0e948.mailgun.org',
}

# or sendgrid.EmailBackend, or...
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
# if you don't already have this in settings
DEFAULT_FROM_EMAIL = "jimjunior854@gmail.com"
# ditto (default from-email for Django errors)
SERVER_EMAIL = "jimjunior854@gmail.com"

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": ["redis://localhost:6379"],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "wnypdbwz",
        'USER': "wnypdbwz",
        'PASSWORD': "xaE6lWJwxA6zhtIFKT1i-ETj7IVV380D",
        'HOST': "rosie.db.elephantsql.com",
        'PORT': "5432",
    }
} """


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

MEDIA_URL = '/useruploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'useruploads')


FLUTTERWAVE_PUBLIC_KEY = "FLWPUBK_TEST-c103ae5a1628c16c68bc77451af5c1f1-X"
FLUTTERWAVE_SECRET = "FLWSECK_TEST-9dbffbbda5a3746b8e37eb4456886097-X"
FLUTTERWAVE_ENDPOINT = "https://api.flutterwave.com/v3"
FLUTTERWAVE_HASH = ""
FLUTTERWAVE_ENCRYPTION_KEY = "FLWSECK_TEST5b63f3a70b92"

GITHUB_WEBHOOK_SECRET = "b3d9b3b0b3d9b3b0b3d9b3b0b3b0b3d9b3bb3d9"

GITHUB_SECRET_HASH = "b3d9b3b0b3d9b3b0b3d9b3b0b3b0b3d9b3bb3d9"
GH_PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAyHV1bh9Fx3+r3DvYSY3mOrlU7MwbASpGyEIvlZWDAqDQvKbq
xvT6eF6GvK9MK/0ODLubsPHWC2vqNUMKWfOd7j6uZHPgrfkHmK4Esh3XSavy1tPk
ryzFt5L+dpvbWLwruNXIuxJlJWOpJH+gdH9gV2+HYgKkKHkHRt6FO0qz/UjwYlPL
7z6LYXr+UxN05FIDV9X+bfNHEQcaszdQaqedu5DIad4M1PzXxsplvwbMtl4XCv1v
6eSz1sWwKZbpbt1YqBNiCbV/xM0pe6XN9D4M4YF27HEvZCqNIKnMkF3jisKTABVD
K+WRQJ6KdOGD3+PolK01VN/aXKRTNpqC1jv5awIDAQABAoIBABmik8Licu0BUbwX
VyCI6gFmhArIS0fJ3UVs2WL6vMdQQ4FsoyeQWpucEwT8MfSKJwrPzyhAtQu+4DOx
gBhixDacg3bLLtdwulz3HBifIlIEkEiSznLsedhxDuOiKNnfLoQzqrjpsE+owA+v
1pgvVeW4mIqbJd0bJSgV+tnLQttIB5rVyLLSEIMuVu7gjiiyf5KcRcwU7EczLK8K
PWqECheLfuJ0kiZiWCn+2JNNdlJZC2vnvhqT7FO/X2gejHhWHqcTgzqLEDgasc+W
B5Jnaw5Owd+h+Tq0WqNHsXe+qlfEVrFXmaOqwAR7AtFqS+4/QWYdQ3QGnJcKPlsL
5Y0WILECgYEA7g5EwyLUCQsunWYnRH2vMBMj6B4tiCMDkxIOvD8buHqO/IGJflqA
z1szZ7UWmb6a/PDxjUJ772BZ75ubwrGASJigUNga1a0YGGBJOrqh3ygn0WeE3O+f
nrVGyCBQO6dRNrQ/kj04HXAGfEpBKvtJur/6LkwzV3L5pzM6lU0drjkCgYEA15Gv
7jx2oBx7DF6Y5BdSBlYz7DWaizZ74btG7Uc04k3ByoEDIohl5r+947wblbn9BdoM
jp000BRw2ThdLwVfDGtivyW+YQ3Aje/W53SnhwQpSbAuD0vHCLMY1J73gf/EnOjE
dtO5hwVQcrVj22V3lQBjrx2gPnDdfLhg20UiZMMCgYA0EQ7dFzsFF1sEthkUk+DD
RQxvclpHElFv011BsxPfD39Cnxpxdl4B/FKL9kGRMu03MYPDf60XuB0zmPdCaAxE
1I0L4ZhM7+T7P+QEYlmRM3kyBdA7enWRAtkOYHLr+TZ8HoRg+d7SIXRprtv+CKQh
omeXxLbeA5mzBjNkAE/jkQKBgQCbIBrDTL1swLIHl7dcRC/hoXzh2T0qOv3w1ezX
aSt0QtJW4HoaCp+R6p9CV6ZeG6Yp5NyucBCGQH9owXfFE49vh4Na3FVg0B2lxlcW
3kqEDYmMnny2wygqaX9P2klwQlcBNzvR6tCSik93DHMceasRDWOuq5oZ9OxeCOyi
PeDfMwKBgQCptbXpRyHKbInQUg0LxrZdiUU+G6EqEUtonTFNqQq3ekRZcNpZJmx+
9stu/Api2hw6gGvENweoWmEv3TmpTzAM9gyXt/1M3xvGrg3SJcI3ONiNlQLTuxx2
DSKQdKVj9AdyfmPQKcyRYOO0XDMDTWd8tctohmAuOEjKqkGCJydKPQ==
-----END RSA PRIVATE KEY-----"""

# Kpack settings
KPACK_URL = "https://kpack.io"
KPACK_DOCKER_REGISTRY = "jimjuniorb/"


# PLatform settings
APP_DEPLOYMENTS_DOMAIN = "cranomapp.ml"


if DEBUG == False:
    from .production import *
