# Generated by Django 4.0.3 on 2022-04-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='replicas',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
