# Generated by Django 4.0.5 on 2022-08-09 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_deployment_replicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='replicas',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='user',
        ),
        migrations.AddField(
            model_name='deployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DeploymentEnvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=1000)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
            ],
        ),
    ]
