# Generated by Django 4.0.5 on 2022-08-09 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deployments', '0004_remove_deployment_image_remove_deployment_replicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='git_repo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
