# Generated by Django 4.0.5 on 2022-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deployment_git_repo_deployment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='env_variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DeploymentEnvs',
        ),
    ]
