# Generated by Django 4.0.5 on 2022-08-12 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_dockerdeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='project_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='dockerdeployment',
            name='project_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dockerdeployment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
