# Generated by Django 4.0.5 on 2022-09-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team'),
        ('deployments', '0008_deployment_project_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
