# Generated by Django 4.0.5 on 2022-09-05 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team'),
        ('deployments', '0009_deployment_deployed_alter_deployment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.IntegerField(blank=True)),
                ('git_repo', models.CharField(blank=True, max_length=200, null=True)),
                ('deployment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('run_command', models.CharField(blank=True, max_length=100)),
                ('build_command', models.CharField(blank=True, max_length=100)),
                ('env_variables', models.JSONField(blank=True, null=True)),
                ('deployed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='project_uuid',
            new_name='deployment_uuid',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='deployed',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='env_variables',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='port',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deployment',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployment',
            name='zipped_project',
            field=models.FileField(blank=True, upload_to='delopyments/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='DockerDeployment',
        ),
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deployments.project'),
            preserve_default=False,
        ),
    ]
