# Generated by Django 4.0.5 on 2022-09-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0010_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deployment_uuid',
            new_name='project_uuid',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.project', to_field='name'),
        ),
    ]
