# Generated by Django 4.0.5 on 2022-09-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0011_rename_deployment_uuid_project_project_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_command',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='run_command',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
