# Generated by Django 4.0.5 on 2022-09-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0012_alter_project_build_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.project', to_field='project_uuid'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
