# Generated by Django 4.0.5 on 2022-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0013_alter_deployment_project_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='local', max_length=10),
            preserve_default=False,
        ),
    ]
