# Generated by Django 4.0.5 on 2022-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0014_deployment_image_project_image_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readable_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
