# Generated by Django 4.0.5 on 2022-09-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0015_project_readable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
