# Generated by Django 4.0.5 on 2022-10-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0016_project_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_cfg',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_cfg',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='webhook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
