# Generated by Django 4.0.5 on 2022-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0017_deployment_deployment_cfg_project_project_cfg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='git_revision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
