# Generated by Django 4.0.5 on 2022-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0018_deployment_git_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='pipeline_cfg',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
