# Generated by Django 4.0.5 on 2022-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0019_deployment_pipeline_cfg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gh_update_on_pr_merge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gh_update_on_push',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gh_update_on_release',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
