# Generated by Django 4.0.5 on 2022-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0020_project_gh_update_on_pr_merge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_charged',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plan',
            field=models.CharField(choices=[('hobby', 'hobby'), ('micro', 'micro'), ('standard', 'standard'), ('medium', 'medium'), ('large', 'large'), ('xlarge', 'xlarge'), ('2xlarge', '2xlarge')], default='free', max_length=10),
        ),
    ]
