# Generated by Django 4.0.5 on 2023-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0022_project_bill_accumulated_project_started_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gh_update_on_push',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
