# Generated by Django 4.0.5 on 2023-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0023_alter_project_gh_update_on_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_repo_pswd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='git_repo_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
