# Generated by Django 4.0.5 on 2023-02-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0024_project_git_repo_pswd_project_git_repo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='run_command',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_command', models.CharField(blank=True, max_length=100, null=True)),
                ('node_type', models.CharField(max_length=10)),
                ('plan', models.CharField(choices=[('hobby', 'hobby'), ('micro', 'micro'), ('standard', 'standard'), ('medium', 'medium'), ('large', 'large'), ('xlarge', 'xlarge'), ('2xlarge', '2xlarge')], default='free', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.project', to_field='project_uuid')),
            ],
        ),
    ]
