# Generated by Django 4.0.5 on 2023-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0025_remove_project_plan_remove_project_run_command_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=48, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('web', 'web'), ('job', 'job')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='plan',
            field=models.CharField(choices=[('hobby', 'hobby'), ('micro', 'micro'), ('standard', 'standard'), ('medium', 'medium'), ('large', 'large'), ('xlarge', 'xlarge'), ('2xlarge', '2xlarge')], default='hobby', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('git', 'git'), ('local', 'local'), ('docker', 'docker'), ('template', 'template')], max_length=10),
        ),
    ]
