# Generated by Django 4.0.5 on 2023-02-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0026_node_name_node_port_alter_node_node_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='build_command',
        ),
        migrations.RemoveField(
            model_name='project',
            name='git_repo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='git_repo_pswd',
        ),
        migrations.RemoveField(
            model_name='project',
            name='git_repo_username',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='port',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='domainname',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deployments.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='bill_accumulated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='build_commands',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='env_variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='git_repo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='git_repo_pswd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='git_repo_username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='process_type',
            field=models.CharField(choices=[('web', 'web'), ('job', 'job')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='node',
            name='started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='stopped_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('git', 'git'), ('local', 'local'), ('docker', 'docker'), ('template', 'template')], max_length=10),
        ),
    ]
