# Generated by Django 4.0.5 on 2023-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0027_remove_project_build_command_remove_project_git_repo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='process_type',
            field=models.CharField(choices=[('web', 'web'), ('worker', 'worker')], default='web', max_length=10),
        ),
    ]
