# Generated by Django 4.0.5 on 2023-02-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0028_alter_node_id_alter_node_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='nodes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='git_revision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='zipped_project',
            field=models.FileField(blank=True, null=True, upload_to='delopyments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='node',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.project', to_field='project_uuid'),
        ),
    ]
