# Generated by Django 4.0.5 on 2023-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0029_deployment_nodes_node_git_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='running',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
