# Generated by Django 4.0.5 on 2023-02-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0030_node_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='custom_git_repo',
            field=models.BooleanField(default=False),
        ),
    ]
