# Generated by Django 4.0.5 on 2023-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0031_node_custom_git_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='build_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='network_protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('SCTP', 'SCTP')], default='TCP', max_length=10),
        ),
    ]
