# Generated by Django 4.0.5 on 2023-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0032_node_build_status_node_network_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='git_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
