# Generated by Django 4.0.5 on 2023-03-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0033_node_git_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='build_status',
            field=models.CharField(default='scheduled', max_length=10),
        ),
    ]
