# Generated by Django 4.0.5 on 2023-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0034_deployment_build_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_public_repo',
            field=models.BooleanField(default=False),
        ),
    ]
