# Generated by Django 4.0.5 on 2023-10-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_notification_options'),
        ('deployments', '0035_node_is_public_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainname',
            name='project',
        ),
        migrations.AddField(
            model_name='domainname',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.node'),
        ),
    ]
