# Generated by Django 4.0.5 on 2023-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0036_remove_domainname_project_domainname_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='domain_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
