apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base-stack
spec:
  id: "heroku-20"
  buildImage:
    image: "heroku/heroku:20-cnb-build"
  runImage:
    image: "heroku/heroku:20-cnb"