apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default-builder
  namespace: default
spec:
  # Cluster service account
  serviceAccountRef:
    name: kpack-sva
    namespace: default
  # Builder tag
  tag: paketobuildpacks/builder:base
  stack:
    name: base-stack
    kind: ClusterStack
  store:
    name: default-store
    kind: ClusterStore