apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.6
        args:
        - --source=ingress # ingress is also possible
        - --provider=linode
        env:
        - name: LINODE_TOKEN
          value: "7dd6d7337c8ed1948456e6b67072a1588a32382cddf6fe73aa6f2170b9db170a"