apiVersion: v1
kind: Secret
metadata:
  name: docker-configjson
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "amltanVuaW9yYjpjaHJpc2Jyb3duYWxzaW5h"
        }
      }
    }


