apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1Ea3hOekUwTkRNek5Gb1hEVE15TURreE5ERTBORE16TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT05lCkNKY21rR21EbW9ybGVGWFV5Znl2Z3E5WkZvenNzV3NnekJWdnNMdE94WFE1cVN3Uk5ndEwvODZxaWxsdDkwR0IKcVRhenFzTUdNcE1xWVl6UUUwVERsZGNtaUFiVVZmQ3hROXZidzZPd21KeDJtaHFxbkI0T2owNXh2NG1MbnM0VgptY29WcmdLS2d1Y0NlTkR0bTMvTmlSVmo0eTBqZEtoNUk0ci9mNUJMYTFrS0lEMlhEWTRtYjJ2WFI0UjlRQWFnCjZkcTZEOUNrN2pJbHJ1MTQyZHBlYTBrR0xZMUR4bTZVRERxakYyVE5aNEZLZjZrQVN3VjFjdmdHcmVNYStUMzcKTHJIeURaQUZSSlJMNHd5OGlyNUcrOHI0Q1dSbDZ1TXhTeHNaN0s5bzBPRUhjdkNFeW9xLzVveW5zeVh5ZmFCbwpRSjI1aWFqbGE5bzNFTVhlMmRNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIa3Y5TDZyMXM1UHl4Yk0zY0FmaG1qSSttNzZNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRXc0eDJ1Mk80RlJsUkxBKzNPegoxeVFmTFJwcnBiU09Ia2NyR0FwU0ZRWlJUeFd2cm9yQnB1aWZIeDZFNTRVUVYzS1owaTh4eUdqU0toWVpnZGxmCmg3VHFzb1pTdExZYzkrOExmQnYvZkV1Q1NEanRYOEY4SHVOeWozNW5XNjF2UER5dmhqMlBkRHZRcHUwdE84UkwKTExWVjNPWjJoMFdObWRjOFVQTjFFYkxIZmVZckJLZ2tOWWNLaElzcTd4TGs4OCtTakovc3Z0ZEZnVGZidUVJNgozRWwrWjA2L0pJZ3hZUGc2MWRKSkNKMFVuSG5GbVBjNHpOWHZaVTdmVEE0dEtNRkFOSWJNRnBUaHhMWEpQWktXCnozV3JRMFhXekxDN0VNZngrQkIyaGJMUlNlOVFyUUtSU1IzcHFuMnlOY0g3TTUvbmpWRU5NRllYQm85RnN3SE0KeTUwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://d0775118-fd93-404d-be46-1abe2ba35aba.ap-south-2.linodelke.net:443
    name: lke72932

users:
  - name: lke72932-admin
    user:
      as-user-extra: {}
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im54ZVRSMnVobjhZSENQcUZ2OE5HNmVqT2J2TUxOdjNLYzZjS0pQaWhYM0kifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tdndzanIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMDdjYWVhNTEtNTRlMy00MDQ3LTlmNjQtZjk4MGI2YTcwYTg2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.ms8URZm_8xL-pyp2SwgxIJ62DNawNoe8OO5Tk75b5ieXzmYilmjcpnJLut06H4-oY0pqSzmcPAll3i-zN_lvJuZrz9oSLmRWXu0T96AXtfy_i7yqjizIZRYxhgQmAZpjD3dyhi2CbWL3rccaFHKJMYORECFBo3q84XkgSqS4ggVOzI6Z0n7flDYDbFJMvhMur8Lf7DDcIqUaD2eq8VIog_CpTScLES-ldMGHu9yXtpeciBSlZ3nV_hXEeq5PX3q3NeB-dlaFpDzxG3OcWEXBvaTpS4AA_Wq9heIIaW2xI_3zz__6G0f7U4J1aI38paS5-nPmK4Kd2Fk4jovnK0pd7A

contexts:
  - context:
      cluster: lke72932
      namespace: default
      user: lke72932-admin
    name: lke72932-ctx

current-context: lke72932-ctx
