# Generated by Django 4.0.5 on 2022-11-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_userprofile_avatar_userprofile_gh_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gh_account_id', models.IntegerField()),
                ('suspended', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to='users.userprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to='users.team')),
            ],
            options={
                'verbose_name': 'Github Installation',
                'verbose_name_plural': 'Github Installations',
            },
        ),
    ]
