# Generated by Django 4.0.5 on 2023-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
